### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by dota-st** [CoreyD97/BurpCustomizer#10]
no apply

**Comment by Chan9390** [comment]
Same here... But found that the apply button is hidden down.

![image](https://user-images.githubusercontent.com/12944530/111076212-6d529900-8511-11eb-875b-8e7a8100cc4d.png)

**Comment by Chan9390** [comment]
Also, the "Apply" button is pushed downwards with different selected themes.

Arc theme: Apply button is not really visible

![image](https://user-images.githubusercontent.com/12944530/111076462-5e201b00-8512-11eb-985a-78b05365ae63.png)

Cobalt 2: Apply button is merely visible.

![image](https://user-images.githubusercontent.com/12944530/111076508-8c055f80-8512-11eb-8912-56f01fe41847.png)

**Comment by CoreyD97** [comment]
Fixed as of V1.0.3
