### ISSUE TITLE
[BUG] Burp freezes when we open existing project.

### ISSUE THREAD

**Issue by nbsriharsha** [CoreyD97/BurpCustomizer#11]
**Describe the bug**
When I open an existing project, the burp customizer popups a message box with no text and freezes the burp UI.

**To Reproduce**
1. Open an existing project which has burp customizer enabled.
2. You can see a message box with no text and the UI won't respond.

**Screenshots**
![BurpSuitePro](https://user-images.githubusercontent.com/9265645/111106451-2bf6d380-857b-11eb-842b-f2105acce81d.png)

**Versions (please complete the following information):**
 - OS: Windows 10
 - Burp Suite Pro 
 - Burp Suite Version: 2021.3

**Comment by CoreyD97** [comment]
Thanks for the report.

I haven't been able to reproduce this behavior. Can you confirm if this is happening every time?
