### ISSUE TITLE
[BUG] Theme not applied on Proxy filter settings

### ISSUE THREAD

**Issue by Chan9390** [CoreyD97/BurpCustomizer#12]
**Description**
The theme selected in Customizer is not applied to proxy filter settings. The proxy filter settings use the base theme (Light / Dark) selected in the User interface section. 

**To Reproduce**
1. Go to User Options -> Display -> User Interface. Select Dark.
2. Go to Customizer -> Select Arc and Apply
3. Go to Proxy -> HTTP History and Click Filter. You'll see that the Arc theme is not applied to the Filter section.

**Screenshots**
![image](https://user-images.githubusercontent.com/12944530/111571755-4e802b00-87cd-11eb-88d4-ad999d71be9a.png)

**Versions (please complete the following information):**
 - OS: Linux
 - Burp Suite Pro / Community: Community
 - Burp Suite Version: 2021.3.1

**Comment by CoreyD97** [comment]
I believe this was fixed in a later version of Burp Suite. Let me know if you still have issues and I will reopen.
