### ISSUE TITLE
Sort the theme list alphabetically

### ISSUE THREAD

**Issue by parsiya** [CoreyD97/BurpCustomizer#3]
**Is your feature request related to a problem? Please describe.**
When I click on `Select Themes` I see two list of themes (each sorted alphabetically). This means I have to scroll down each list individually to figure out which themes are available.

**Describe the solution you'd like**
Sort all  themes alphabetically, together.

**Describe alternatives you've considered**
More scrolling.

As you can see in the screenshot below, the first list ends as `Vuesion` and then second list starts with `Arc Dark (Material)`.

![image](https://user-images.githubusercontent.com/3981231/103489243-d60dee80-4dc7-11eb-9f2c-be2f16cf98da.png)

Thanks for the extension. This is great.

**Comment by CoreyD97** [comment]
Good idea, I should have done this to start with!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
