### ISSUE TITLE
[FR] Is it possible to update it for Burp 1.7.*

### ISSUE THREAD

**Issue by hetroublemaker** [CoreyD97/BurpCustomizer#5]
It would be really great If this extension works on the older version of Burp too.

**Comment by CoreyD97** [comment]
Unfortunately the older versions of Burp have a lot of hardcoded color values, and so most of the UI elements will remain their old color when applying the theme, so this is something I won't implement unfortunately!

**Comment by hetroublemaker** [comment]
No worries! I used the latest version of Burp and burp customizer is
awesome!
