### ISSUE TITLE
No Theme Showing in Customizer tab

### ISSUE THREAD

**Issue by f4t7** [CoreyD97/BurpCustomizer#9]
I'm currently using Burp 2020.91, By default it shows Arc and there's no list showing up on clicking the arrow.
![Screenshot_20210224_203045](https://user-images.githubusercontent.com/40952846/109024153-43ab0c80-76df-11eb-8918-4b9d79c53801.png)

**Comment by CoreyD97** [comment]
Thanks for the report. Can you confirm your Burp Suite version? This extension is only compatible with Burp Suite 2020.12 and above.
